### ISSUE TITLE
Exception in latest docker image if there is groovy script

### ISSUE THREAD

**Issue by cgi** [structurizr/structurizr#109]
We have workspace.dsl + groovy script for generating views.

Today after image rebuild from docker hub there is Exception in logs:
```
17-Aug-2022 13:25:29.946 SEVERE [http-nio-8080-exec-10] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [root] in context with path [] threw exception [Handler dispatch failed; nes
ted exception is java.lang.ExceptionInInitializerError] with root cause
        groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-jsr223 is loaded in version 3.0.12 and you are trying to load version 3.0.8
                at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:510)
                at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:87)
                at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromMetaInf(ExtensionModuleScanner.java:81)
                at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModulesFrom(ExtensionModuleScanner.java:63)
                at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModules(ExtensionModuleScanner.java:54)
                at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:125)
                at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
                at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:37)
                at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:88)
                at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:46)
                at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
                at groovy.lang.Binding.<init>(Binding.java:36)
                at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl$2.<init>(GroovyScriptEngineImpl.java:222)
                at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:222)
                at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155)
                at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:231)
                at com.structurizr.dsl.ScriptDslContext.run(ScriptDslContext.java:24)
                at com.structurizr.dsl.ExternalScriptDslContext.end(ExternalScriptDslContext.java:29)
                at com.structurizr.dsl.StructurizrDslParser.endContext(StructurizrDslParser.java:841)
                at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:758)
                at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:125)
```

**Comment by simonbrowndotje** [comment]
This should now be fixed in build 2780.

**Comment by cgi** [comment]
Thanks for super fast reaction!
Just checked last version - our case work just fine as before!
