### ISSUE TITLE
Dynamic diagram with custom elements

### ISSUE THREAD

**Issue by aidmax** [structurizr/structurizr#118]
Hello, 

I'm trying to create a dynamic diagram that includes custom element, but receiving the `The destination element ... should be a static structure element at line ...` error. 

The workspace file

```
workspace {

    model {
        user = person "User" "A user of my software system."
        softwareSystem = softwareSystem "Software System" "My software system."

        custom = element "Box" "" "A description" ""

        user -> softwareSystem "Uses"
    }

    views {
        systemContext softwareSystem "SystemContext" {
            include *
            autoLayout
        }
        dynamic softwareSystem {
            user -> custom "uses"

        styles {
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427b
                color #ffffff
            }
        }
    }
    
}
```

The log file

```
31-Aug-2022 12:48:39.646 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [8,963] ms
31-Aug-2022 12:48:39.652 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
31-Aug-2022 12:48:39.668 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [9052] milliseconds
java.lang.RuntimeException: The destination element "custom" should be a static structure element
	at com.structurizr.dsl.DynamicViewContentParser.parseRelationship(DynamicViewContentParser.java:52)
	at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:655)
	at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:125)
	at com.structurizr.lite.component.workspace.FileSystemWorkspaceComponent.loadWorkspaceFromDsl(FileSystemWorkspaceComponent.java:132)
	at com.structurizr.lite.component.workspace.FileSystemWorkspaceComponent.loadWorkspace(FileSystemWorkspaceComponent.java:98)
	at com.structurizr.lite.component.workspace.FileSystemWorkspaceComponent.getWorkspace(FileSystemWorkspaceComponent.java:166)
	at com.structurizr.lite.web.HomeController.showDefaultPage(HomeController.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 2022-08-31 12:48:59.577 [http-nio-8080-exec-6] FileSystemWorkspaceComponent - com.structurizr.dsl.StructurizrDslParserException: The destination element "custom" should be a static structure element at line 18: user -> custom "uses"
[ERROR] 2022-08-31 12:48:59.584 [http-nio-8080-exec-6] Http500Controller - null
```

Environment
```
[INFO ] 2022-08-31 12:52:40.392 [main] Configuration -  Structurizr Lite
[INFO ] 2022-08-31 12:52:40.394 [main] Configuration -  Build: 2781
[INFO ] 2022-08-31 12:52:40.397 [main] Configuration -  Built: 2022-08-19T11:23:46Z
[INFO ] 2022-08-31 12:52:40.420 [main] Configuration -  Structurizr DSL: v1.20.0
```

**Comment by simonbrowndotje** [comment]
This is now available in Lite and the demo page ([example](https://structurizr.com/dsl?src=https://gist.githubusercontent.com/simonbrowndotje/46fa3748ee0ac3dd208c4709920822cb/raw/a0997c5e4538137952fc34e144197fb37392e0e5/workspace.dsl)).
