### ISSUE TITLE
Structurizr/lite throws an error shortly after intialization

### ISSUE THREAD

**Issue by pyrrho** [structurizr/structurizr#127]
Shortly after starting the structurizr/lite docker image (2850) and agreeing to the EULA on localhost, the web app throws an "Workspace 1 could not be saved using the API at http://localhost:8080/api" error message. The status is 400 - error, and no message is provided. The docker image throws a Java exception, though:

```
2022-11-01 14:42:13.480  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2022-11-01 14:42:34.710  INFO 1 --- [nio-8080-exec-7] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Request header is too large
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:790) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at org.apache.coyote.http11.Http11InputBuffer.parseHeader(Http11InputBuffer.java:971) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at org.apache.coyote.http11.Http11InputBuffer.parseHeaders(Http11InputBuffer.java:604) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:294) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

I launched structurizr with `sudo docker run -it --rm -p 8080:8080 -v /home/dpb/structurizr_test:/usr/local/structurizr structurizr/lite`, and can confirm that the image is able to read from and write to `/home/dpb/structurizr_test` -- workspace.json and the .structurizr directory are populated, and the server updates the document described in workspace.dsl as I edit it.

I'm just met with an error modal about three seconds after I reload the page.

The system I'm running is Pop!_OS 22.04 with the Docker CLI version 20.10.21.

**Comment by simonbrowndotje** [comment]
Can you see the offending request from the developer tools/console in your web browser? If not, perhaps another application is also trying to send data to port 8080?

**Comment by pyrrho** [comment]
Oh Jeez. I can't believe I missed that. A cookie from another application -- targeting a different port, and not actively running -- is being forwarded to everything running on localhost. This was just me missing a detail of my own system, overloading tomcat.

Thanks for the reply, and for the tool!
