### ISSUE TITLE
documentation cannot be added in structurizr lite

### ISSUE THREAD

**Issue by krnkl** [structurizr/structurizr#53]
strange error `Content must be specified at line 4: !docs docs` is shown when trying to add docs to the project.

workspace file:
```
workspace {
    !adrs adrs
    !docs docs
    model {
    }

    views {
    }
}
```

error from logs:
```
[ERROR] 2021-12-29 11:11:55.847 [http-nio-8080-exec-9] FileSystemWorkspaceComponent - com.structurizr.dsl.StructurizrDslParserException: Content must be specified at line 4: !docs docs
[ERROR] 2021-12-29 11:11:55.850 [http-nio-8080-exec-9] ApiController - com.structurizr.lite.web.ApiException: workspace.dsl: Content must be specified at line 4: !docs docs
java.lang.IllegalArgumentException: Content must be specified.
	at com.structurizr.documentation.Documentation.checkContentIsSpecified(Documentation.java:61)
	at com.structurizr.documentation.Documentation.addSection(Documentation.java:44)
	at com.structurizr.documentation.DocumentationTemplate.add(DocumentationTemplate.java:144)
	at com.structurizr.documentation.DocumentationTemplate.addSection(DocumentationTemplate.java:88)
	at com.structurizr.documentation.AutomaticDocumentationTemplate.add(AutomaticDocumentationTemplate.java:108)
	at com.structurizr.documentation.AutomaticDocumentationTemplate.addSections(AutomaticDocumentationTemplate.java:55)
	at com.structurizr.dsl.DocsParser.parse(DocsParser.java:50)
	at com.structurizr.dsl.DocsParser.parse(DocsParser.java:17)
	at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:666)
	at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:122)
	at com.structurizr.lite.component.workspace.FileSystemWorkspaceComponent.loadWorkspaceFromDsl(FileSystemWorkspaceComponent.java:128)
	at com.structurizr.lite.component.workspace.FileSystemWorkspaceComponent.loadWorkspace(FileSystemWorkspaceComponent.java:94)
	at com.structurizr.lite.component.workspace.FileSystemWorkspaceComponent.getWorkspace(FileSystemWorkspaceComponent.java:162)
	at com.structurizr.lite.web.ApiController.getWorkspace(ApiController.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 2021-12-29 11:11:59.254 [http-nio-8080-exec-4] FileSystemWorkspaceComponent - com.structurizr.dsl.StructurizrDslParserException: Content must be specified at line 4: !docs docs
[ERROR] 2021-12-29 11:11:59.257 [http-nio-8080-exec-4] ApiController - com.structurizr.lite.web.ApiException: workspace.dsl: Content must be specified at line 4: !docs docs
```
docs folder is present:
```
$ tree docs/
docs/
├── 00_TODO.md
└── 01-context.md
```

```
$ docker image inspect structurizr/lite
[
    {
        "Id": "sha256:eb44616692d9c733873cffbb3383ed998d85da773b71442b51b999022504f22c",
        "RepoTags": [
            "structurizr/lite:latest"
        ],
        "RepoDigests": [
            "structurizr/lite@sha256:cc3145d5e3c1188675f81a9c18474610a5e65417de6db2dac8cba18940010039"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2021-12-29T10:31:21.5862274Z",
```

**Comment by krnkl** [comment]
same error is shown when `!docs` directive added either to workspace or softwaresystem, accoording [to the dsl reference](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#documentation)

**Comment by krnkl** [comment]
adrs are shown fine

**Comment by simonbrowndotje** [comment]
Is one of your documentation files empty?

**Comment by krnkl** [comment]
Yes, is was.
now error message makes sense.
Thanks for a quick reply
