### ISSUE TITLE
Structurizr does not load workspace at all

### ISSUE THREAD

**Issue by fizyk** [structurizr/structurizr#56]
Most recent latest lite image does not load the workspace nor any view. 

Docker's CPU usage skyrockets and docker image has only this exception in logs:

```
2022-02-02T10:23:22.644070923Z NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
2022-02-02T10:23:23.341455884Z 02-Feb-2022 10:23:23.313 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.41
2022-02-02T10:23:23.341771099Z 02-Feb-2022 10:23:23.341 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Dec 3 2020 11:43:00 UTC
2022-02-02T10:23:23.342052439Z 02-Feb-2022 10:23:23.341 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.41.0
2022-02-02T10:23:23.342299764Z 02-Feb-2022 10:23:23.342 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
2022-02-02T10:23:23.342501339Z 02-Feb-2022 10:23:23.342 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.13.0-27-generic
2022-02-02T10:23:23.342898833Z 02-Feb-2022 10:23:23.342 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
2022-02-02T10:23:23.343103831Z 02-Feb-2022 10:23:23.342 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-11
2022-02-02T10:23:23.343311553Z 02-Feb-2022 10:23:23.343 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.10+9
2022-02-02T10:23:23.343538413Z 02-Feb-2022 10:23:23.343 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
2022-02-02T10:23:23.343713029Z 02-Feb-2022 10:23:23.343 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
2022-02-02T10:23:23.343868436Z 02-Feb-2022 10:23:23.343 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
2022-02-02T10:23:23.367410119Z 02-Feb-2022 10:23:23.367 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
2022-02-02T10:23:23.367452864Z 02-Feb-2022 10:23:23.367 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
2022-02-02T10:23:23.367560567Z 02-Feb-2022 10:23:23.367 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
2022-02-02T10:23:23.367662193Z 02-Feb-2022 10:23:23.367 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
2022-02-02T10:23:23.367741678Z 02-Feb-2022 10:23:23.367 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
2022-02-02T10:23:23.367836110Z 02-Feb-2022 10:23:23.367 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
2022-02-02T10:23:23.367976849Z 02-Feb-2022 10:23:23.367 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
2022-02-02T10:23:23.368105157Z 02-Feb-2022 10:23:23.368 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
2022-02-02T10:23:23.368232626Z 02-Feb-2022 10:23:23.368 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms256M
2022-02-02T10:23:23.368337115Z 02-Feb-2022 10:23:23.368 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx256M
2022-02-02T10:23:23.368484072Z 02-Feb-2022 10:23:23.368 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
2022-02-02T10:23:23.368594778Z 02-Feb-2022 10:23:23.368 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
2022-02-02T10:23:23.368716310Z 02-Feb-2022 10:23:23.368 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
2022-02-02T10:23:23.368788740Z 02-Feb-2022 10:23:23.368 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
2022-02-02T10:23:23.380851643Z 02-Feb-2022 10:23:23.380 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.25] using APR version [1.6.5].
2022-02-02T10:23:23.380892363Z 02-Feb-2022 10:23:23.380 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
2022-02-02T10:23:23.381007539Z 02-Feb-2022 10:23:23.380 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
2022-02-02T10:23:23.384581631Z 02-Feb-2022 10:23:23.384 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1d  10 Sep 2019]
2022-02-02T10:23:23.947813580Z 02-Feb-2022 10:23:23.947 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
2022-02-02T10:23:23.989565316Z 02-Feb-2022 10:23:23.989 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [988] milliseconds
2022-02-02T10:23:24.089264402Z 02-Feb-2022 10:23:24.088 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
2022-02-02T10:23:24.089594843Z 02-Feb-2022 10:23:24.089 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.41]
2022-02-02T10:23:24.096620517Z 02-Feb-2022 10:23:24.093 SEVERE [main] org.apache.catalina.startup.HostConfig.beforeStart Unable to create directory for deployment: [/usr/local/tomcat/conf/Catalina/localhost]
2022-02-02T10:23:24.114250987Z 02-Feb-2022 10:23:24.113 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
2022-02-02T10:23:24.142554839Z 02-Feb-2022 10:23:24.141 SEVERE [main] org.apache.catalina.startup.ContextConfig.beforeStart Exception fixing docBase for context []
2022-02-02T10:23:24.142590740Z 	java.io.IOException: Unable to create the directory [/usr/local/tomcat/webapps/ROOT]
2022-02-02T10:23:24.142597026Z 		at org.apache.catalina.startup.ExpandWar.expand(ExpandWar.java:115)
2022-02-02T10:23:24.142642845Z 		at org.apache.catalina.startup.ContextConfig.fixDocBase(ContextConfig.java:820)
2022-02-02T10:23:24.142648992Z 		at org.apache.catalina.startup.ContextConfig.beforeStart(ContextConfig.java:958)
2022-02-02T10:23:24.142654160Z 		at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:305)
2022-02-02T10:23:24.142659469Z 		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
2022-02-02T10:23:24.142663380Z 		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
2022-02-02T10:23:24.142668619Z 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:182)
2022-02-02T10:23:24.142673787Z 		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
2022-02-02T10:23:24.142679096Z 		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
2022-02-02T10:23:24.142684264Z 		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
2022-02-02T10:23:24.142689014Z 		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
2022-02-02T10:23:24.142693903Z 		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1848)
2022-02-02T10:23:24.142711504Z 		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2022-02-02T10:23:24.142716184Z 		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-02-02T10:23:24.142721492Z 		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
2022-02-02T10:23:24.142726800Z 		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
2022-02-02T10:23:24.142732039Z 		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
2022-02-02T10:23:24.142736788Z 		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
2022-02-02T10:23:24.142741957Z 		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
2022-02-02T10:23:24.142747265Z 		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
2022-02-02T10:23:24.142752434Z 		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
2022-02-02T10:23:24.142757323Z 		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
2022-02-02T10:23:24.142763539Z 		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
2022-02-02T10:23:24.142769197Z 		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
2022-02-02T10:23:24.142774854Z 		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
2022-02-02T10:23:24.142786379Z 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2022-02-02T10:23:24.142797415Z 		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
2022-02-02T10:23:24.142803002Z 		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
2022-02-02T10:23:24.142808171Z 		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-02-02T10:23:24.142813479Z 		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
2022-02-02T10:23:24.142818788Z 		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
2022-02-02T10:23:24.142824166Z 		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
2022-02-02T10:23:24.142829334Z 		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
2022-02-02T10:23:24.142834503Z 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2022-02-02T10:23:24.142840091Z 		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:434)
2022-02-02T10:23:24.142845329Z 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2022-02-02T10:23:24.142850568Z 		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
2022-02-02T10:23:24.142855876Z 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2022-02-02T10:23:24.142861114Z 		at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
2022-02-02T10:23:24.142866423Z 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-02-02T10:23:24.142871591Z 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-02-02T10:23:24.142876760Z 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-02-02T10:23:24.142882487Z 		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-02-02T10:23:24.142888284Z 		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
2022-02-02T10:23:24.142893593Z 		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
```

**Comment by simonbrowndotje** [comment]
It's all working fine for me ... perhaps check that you have enough disk space allocated, etc.

**Comment by fizyk** [comment]
Okay, it seems that it was because we passed different `--user` to `docker run` (to make sure the running user owned generated/changed files).
