### ISSUE TITLE
groups error from Github Actions

### ISSUE THREAD

**Issue by psacchitella** [structurizr/structurizr#71]
Hello,
I am running the  gilbertotcc/structurizr-action@v1 Github Action to push workspace.dsl file to an on-prem instance of structurizr. It looks like it is running the latest image but I am seeing the following error:
` Caused by: com.structurizr.dsl.StructurizrDslParserException: Unexpected tokens at line 11: service1 = group "Service 1" {
	at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:448) ~[structurizr-dsl-1.0.0.jar!/:na]
	at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:75) ~[structurizr-dsl-1.0.0.jar!/:na]
	at com.structurizr.cli.PushCommand.run(PushCommand.java:120) ~[classes!/:na]
	at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:36) ~[classes!/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]`

When I run the same CLI command from my workstation or the docker image running locally. It works as expected. Is there an update I can apply to this?

**Comment by simonbrowndotje** [comment]
The stacktrace includes `structurizr-dsl-1.0.0.jar`, which is a very old version of the DSL parser. You'll need to raise an issue on [gilbertotcc/structurizr-action](https://github.com/gilbertotcc/structurizr-action).

**Comment by psacchitella** [comment]
Thank you. I just did a work around for now.
