### ISSUE TITLE
Unable to use my own ImpliedRelationshipsStrategy

### ISSUE THREAD

**Issue by lhauspie** [structurizr/structurizr#97]
I tried to write and use my own `ImpliedRelationshipsStrategy`.

For test purpose, this is my first version in the package `com.structurizr.model` in my maven project:
```java
package com.structurizr.model;

public class NoImpliedRelationshipsStrategy extends AbstractImpliedRelationshipsStrategy {
    public NoImpliedRelationshipsStrategy() {
    }

    public void createImpliedRelationships(Relationship relationship) {
        // Just do nothing for now. To be implemented later.
    }
}
```

I built my jar file and then ran Structurizr Lite with this command:
```
docker run --rm --name structurizr-lite -p 18080:8080 -v $PWD/src/main/resources:/usr/local/structurizr -v $PWD/target/my-strategy-1.0.0-SNAPSHOT.jar:/usr/local/tomcat/lib/my-strategy.jar structurizr/lite
```

My workspace file is located here `./src/main/ressources/workspace.dsl` and starts with this piece of code:
```
workspace {
	!script groovy {
		workspace.getModel().setImpliedRelationshipsStrategy(new com.structurizr.model.NoImpliedRelationshipsStrategy());
	}

	model {
		...
	}
}
```

But When I go to http://locahost:18080/ I have this error on the front-end:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/52406406/178698829-468bf368-cf31-4215-b00d-f084a47782da.png">

The WebDevConsole displays this:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/25682509/178705207-693d9b03-be3b-408d-9aa2-d4c03e0d9ff0.png">

And the back-end displays this:
```
[WARN ] 2022-07-13 09:22:50.228 [http-nio-8080-exec-9] ExceptionHandlerExceptionResolver - Failed to invoke @ExceptionHandler method: public com.structurizr.lite.web.ApiResponse com.structurizr.lite.web.ApiController.error(javax.servlet.http.HttpServletResponse,java.lang.String)
java.lang.IllegalStateException: Could not resolve method parameter at index 1 in public com.structurizr.lite.web.ApiResponse com.structurizr.lite.web.ApiController.error(javax.servlet.http.HttpServletResponse,java.lang.String): No suitable resolver for argument 1 of type 'java.lang.String'
        at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:171) ~[spring-web-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:127) ~[spring-web-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:381) [spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:59) [spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.resolveException(AbstractHandlerExceptionResolver.java:131) [spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1222) [spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1034) [spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984) [spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) [servlet-api.jar:4.0.FR]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [servlet-api.jar:4.0.FR]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [catalina.jar:9.0.59]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.59]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.59]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.59]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.59]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.59]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.59]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) [spring-web-4.3.30.RELEASE.jar:4.3.30.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.59]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.59]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [catalina.jar:9.0.59]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:9.0.59]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.59]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:9.0.59]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.59]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [catalina.jar:9.0.59]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:9.0.59]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359) [catalina.jar:9.0.59]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat-coyote.jar:9.0.59]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.59]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) [tomcat-coyote.jar:9.0.59]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) [tomcat-coyote.jar:9.0.59]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.59]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.59]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.59]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.59]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

The front-end seems to "back-POST" the error to the backend and fails for some reasons I can't identify.

For additional information, if I remove my jar from tomcat libs by running Structurizr Lite with thhis command:
```
docker run --rm --name structurizr-lite -p 18080:8080 -v $PWD/src/main/resources:/usr/local/structurizr structurizr/lite 
```

The error is not the same:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/52406406/178700473-318ce85d-8f92-4fef-a9c3-d1c703859f78.png">

So this makes me say that my `ImpliedRelationshipsStrategy` class is correctly found by tomcat but the error handling failed to manage the error.

I think, this errorHandling problem hides my own error so I'm not able to understand what's going wrong.

Am I missing something ?  
Is it even possible to implement my own `ImpliedRelationshipsStrategy` ?

Thanks in advance.

**Comment by simonbrowndotje** [comment]
I'm not entirely sure what happens if you try to add classes to the Tomcat classloader that depend upon classes in the web application's classloader, so I'd recommend writing this as a plugin instead (see https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#plugins) ... I just tried doing this and it worked as expected.

1. Create a new project with dependencies on `structurizr-dsl` and `structurizr-core`.
2. Create your strategy; for example:

```
package com.example;

import com.structurizr.model.AbstractImpliedRelationshipsStrategy;
import com.structurizr.model.Relationship;

public class MyImpliedRelationshipsStrategy extends AbstractImpliedRelationshipsStrategy {

    @Override
    public void createImpliedRelationships(Relationship relationship) {
        System.out.println("Hello");
    }
}
```

3. Create a plugin class; for example:

```
package com.example;

import com.structurizr.dsl.StructurizrDslPlugin;
import com.structurizr.dsl.StructurizrDslPluginContext;

public class MyPlugin implements StructurizrDslPlugin {

    @Override
    public void run(StructurizrDslPluginContext context) {
        context.getWorkspace().getModel().setImpliedRelationshipsStrategy(new MyImpliedRelationshipsStrategy());
    }

}
```

5. Build the JAR file, copy to a `plugins` folder next to your `workspace.dsl` file.
6. Use the plugin via `!plugin com.example.MyPlugin`

Hope that helps.

**Comment by lhauspie** [comment]
Thanks for your help @simonbrowndotje.

It works with a simple System.out.println().
But after implementing my logic in my Strategy I'm back to an error.
And the problem is that the exception thrown by my code is not logged.

So to know the origin of my problem, I had to write a catch block to `printStackTrace`.
Maybe it can be an improvement to log the error 🤔

Anyway, to get back to my problem, printing the stack trace of the catched Throwable, I see this kind of trace:
```
CreateImpliedRelationshipsUnlessParentRelationshipsExistStrategy.createImpliedRelationships => {4 | WMS | Warehouse Management System} ---[????? ?? ???? ?? ? ? ????]---> {8 | Doubtful Movements | Stores particular logistic events until reliability action is done}
java.lang.IllegalAccessError: class com.structurizr.model.CreateImpliedRelationshipsUnlessParentRelationshipsExistStrategy tried to access method 'com.structurizr.model.Relationship com.structurizr.model.Model.addRelationship(com.structurizr.model.Element, com.structurizr.model.Element, java.lang.String, java.lang.String, boolean)' (com.structurizr.model.CreateImpliedRelationshipsUnlessParentRelationshipsExistStrategy is in unnamed module of loader java.net.URLClassLoader @79b6c539; com.structurizr.model.Model is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @51650883)
        at com.structurizr.model.CreateImpliedRelationshipsUnlessParentRelationshipsExistStrategy.firstVersion(CreateImpliedRelationshipsUnlessParentRelationshipsExistStrategy.java:19)
        at com.structurizr.model.CreateImpliedRelationshipsUnlessParentRelationshipsExistStrategy.createImpliedRelationships(CreateImpliedRelationshipsUnlessParentRelationshipsExistStrategy.java:9)
        at com.structurizr.model.Model.addRelationship(Model.java:275)
        at com.structurizr.model.Model.addRelationship(Model.java:252)
        at com.structurizr.model.StaticStructureElement.uses(StaticStructureElement.java:259)
        at com.structurizr.dsl.AbstractRelationshipParser.createRelationship(AbstractRelationshipParser.java:15)
        at com.structurizr.dsl.ExplicitRelationshipParser.parse(ExplicitRelationshipParser.java:69)
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:204)
        at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:124)
        at com.structurizr.lite.component.workspace.FileSystemWorkspaceComponent.loadWorkspaceFromDsl(FileSystemWorkspaceComponent.java:132)
        at com.structurizr.lite.component.workspace.FileSystemWorkspaceComponent.loadWorkspace(FileSystemWorkspaceComponent.java:98)
        at com.structurizr.lite.component.workspace.FileSystemWorkspaceComponent.getWorkspace(FileSystemWorkspaceComponent.java:166)
        at com.structurizr.lite.web.ApiController.getWorkspace(ApiController.java:44)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:204)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

For information, my code is very simple and inspired by `CreateImpliedRelationshipsUnlessSameRelationshipExistsStrategy`:
```Java
public class CreateImpliedRelationshipsUnlessParentRelationshipsExistStrategy extends AbstractImpliedRelationshipsStrategy {

    public void createImpliedRelationships(Relationship relationship) {
        System.out.println("CreateImpliedRelationshipsUnlessParentRelationshipsExistStrategy.createImpliedRelationships => " + relationship);
        try {
            Element source = relationship.getSource();
            Model model = source.getModel();
            Element destination = relationship.getDestination();
            Relationship impliedRelationship = model.addRelationship(source, destination, relationship.getDescription(), relationship.getTechnology(), true);
            if (impliedRelationship != null) {
                impliedRelationship.setLinkedRelationshipId(relationship.getId());
            }
        } catch (Throwable e) {
            e.printStackTrace();
            throw new RuntimeException(e);
        }
    }
}
```

Dependencies in `plugins`folder:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/25682509/179200058-a5005d9e-843e-4f46-90a2-03f41e214af4.png">

**Comment by lhauspie** [comment]
To understand what I try to achieve, and to know if I'm using the good or wrong approach, I try to display all children impliedRelationships if there is no relationships between parents.
Let me try wit some examples.

First try:
```
	model {
		externalSystem = softwareSystem "External System" "External System"

		enterprise "My enterprise - My group" {
			internalSystem  = softwareSystem "Internal System" "Internal System" {
				firstContainer  = container "First Container" "First Container" "???" {
					externalSystem -> this "First Relation to firstContainer"
					externalSystem -> this "Second Relation to firstContainer"
				}

				secondContainer = container "Second Container" "Second Container" "???" {
					externalSystem -> this "First Relation to secondContainer"
					externalSystem -> this "Second Relation to secondContainer"
				}
			}
		}
	}
```

will display:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/25682509/179202191-7e92bf49-c7f9-44aa-b67b-e4e2515260f5.png">

Ok, so I have to set the `ImpliedRelationshipsStrategy`:
```
	!script groovy {
		workspace.getModel().setImpliedRelationshipsStrategy(new com.structurizr.model.CreateImpliedRelationshipsUnlessSameRelationshipExistsStrategy());
    }
```

which will display:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/25682509/179202359-b826209d-8215-422d-92e2-f01af1a1bc8f.png">

What songs good to me.

But if I add higher level relationships:
```
	!script groovy {
		workspace.getModel().setImpliedRelationshipsStrategy(new com.structurizr.model.CreateImpliedRelationshipsUnlessSameRelationshipExistsStrategy());
    }

	model {
		externalSystem = softwareSystem "External System" "External System"

		enterprise "My enterprise - My group" {
			internalSystem  = softwareSystem "Internal System" "Internal System" {
==>				externalSystem -> this "First Relation"
				firstContainer  = container "First Container" "First Container" "???" {
					externalSystem -> this "First Relation to firstContainer"
					externalSystem -> this "Second Relation to firstContainer"
				}

==>				externalSystem -> this "Second Relation"
				secondContainer = container "Second Container" "Second Container" "???" {
					externalSystem -> this "First Relation to secondContainer"
					externalSystem -> this "Second Relation to secondContainer"
				}
			}
		}
	}

```
it will display all children relationships and parent relationships:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/25682509/179202787-66001996-23cd-4981-81c7-5adbcaa469b0.png">

where I would like to see only the parent relationships (what is possible by removing the `setImpliedRelationshipsStrategy`):
<img width="255" alt="image" src="https://user-images.githubusercontent.com/25682509/179203160-dc7f2f0b-4af6-4a0a-be3e-07095729f777.png">

What songs wrong to me (too much details).

So it's impossible to make these two behaviors cohabit.
That's why I would like to implement my own strategy to add implied relationships only if parent's ones are missing.

**Comment by lhauspie** [comment]
I also tried to compile my plugin jar with java 1.8 to workaround the module system but without any success :/

Probably due to the JRE version that run Structurizr

Thanks for your responses and time.

**Comment by simonbrowndotje** [comment]
I've just released a new version of Lite, so you can try the following:

1. Update the Lite Docker image.
2. Change the structurizr-core dependency in your plugin project to the version attached to this comment (I've changed the extension to `.zip` in order to attach it, so you'll need to rename it back to `.jar`).
3. Change your implied relationship strategy code to use the new `createImpliedRelationship` method ... I'd also move your implementation class out of the `com.structurizr.model` package, since this won't be needed anymore.
4. To deploy your plugin, you only need the `structurizr-plugin-1.0.0.jar` file in the `plugins` folder ... you don't need any of the dependencies, as they'll already be on Lite's classpath.

[structurizr-core-1.13.1.zip](https://github.com/structurizr/structurizr/files/9121871/structurizr-core-1.13.1.zip)

**Comment by simonbrowndotje** [comment]
v1.14.0 of the structurizr-core library is now available on Maven Central, which includes the above.
